name: slack-build-notifier
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 * * * *'
    - cron:  '10 * * * *'
    - cron:  '20 * * * *'
    - cron:  '30 * * * *'
    - cron:  '40 * * * *'
    - cron:  '50 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test OAM DEV
        run: curl https://oam.dev
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ' :scream: Could someone check and fix our website :rocket:'
          SLACK_TITLE: https://oam.dev is unavailable now
          SLACK_USERNAME: wonderflow
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
