name: slack-build-notifier
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 * * * *'
    - cron:  '5 * * * *'
    - cron:  '10 * * * *'
    - cron:  '15 * * * *'
    - cron:  '20 * * * *'
    - cron:  '25 * * * *'
    - cron:  '30 * * * *'
    - cron:  '35 * * * *'
    - cron:  '40 * * * *'
    - cron:  '45 * * * *'
    - cron:  '50 * * * *'
    - cron:  '55 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test OAM DEV
        run: curl https://oam.test
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: oam.dev web failed
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
